version: "3.8"
services:
  mysql:
    image: mysql
    container_name: testeDevFullStack-DB
    environment:
      MYSQL_DATABASE: testeDevFullStack
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
