version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
